// Fictional sample patients and visit history so the app is testable
// immediately. Interpretations and treatment plans are generated by the
// same reasoning engine the live app uses (see src/services), so the
// seed data and the "AI" stay consistent with each other.
//
// None of this represents real patients, real research findings, or real
// citations - it exists purely to demonstrate the workflow.

import type {
  ExaminationResults,
  ExamRecommendation,
  Patient,
  RedFlagScreen,
  SubjectiveExam,
  TreatmentRecommendation,
  Visit,
} from '../types';
import { recommendExaminations } from '../services/examRecommendationService';
import { interpretFindings } from '../services/patternRecognitionService';
import { planTreatment } from '../services/treatmentPlanningService';

const emptyResults = (): ExaminationResults => ({
  positional: [],
  oculomotor: [],
  vestibularFunction: [],
  balance: [],
  gait: [],
  outcomeMeasures: [],
});

function acceptedRecs(subjective: SubjectiveExam): ExamRecommendation[] {
  return recommendExaminations(subjective).map((r) => ({ ...r, status: 'accepted' as const }));
}

function acceptedPlan(interpretationResults: ReturnType<typeof interpretFindings>): TreatmentRecommendation[] {
  return planTreatment(interpretationResults).map((t) => ({ ...t, status: 'accepted' as const }));
}

const noRedFlags: RedFlagScreen = {
  findings: [],
  therapistAcknowledgement: true,
};

// ---------------------------------------------------------------------
// Patient 1: Maria Gonzalez - right posterior canal BPPV, resolved
// ---------------------------------------------------------------------

const maria: Patient = {
  id: 'pt-maria',
  firstName: 'Maria',
  lastName: 'Gonzalez',
  age: 54,
  sex: 'female',
  createdAt: '2026-07-10T09:00:00.000Z',
};

const mariaV1Subjective: SubjectiveExam = {
  primaryComplaint: 'Brief spinning sensation when rolling over in bed and looking up at shelves.',
  symptomOnset: '5 days ago',
  mechanismOfOnset: 'Spontaneous, first noticed rolling over in bed',
  medicalHistory: 'Hypertension, well-controlled',
  medications: 'Lisinopril',
  fallsHistory: 'No falls',
  assistiveDeviceUse: 'None',
  symptoms: ['vertigo'],
  durations: ['seconds'],
  triggers: ['rollingInBed', 'lookingUp', 'bendingDown'],
  associatedSymptoms: ['nausea'],
  additionalNotes: 'Symptoms are brief but intense; avoiding rolling to the right in bed.',
};

const mariaV1Results: ExaminationResults = {
  positional: [
    {
      test: 'dixHallpike',
      performed: true,
      positive: true,
      side: 'right',
      nystagmusDirection: 'torsional',
      torsionalComponent: true,
      verticalComponent: 'upbeat',
      geoApogeotropic: 'n/a',
      latencySec: 4,
      durationSec: 25,
      fatigable: true,
      reproducedSymptoms: true,
    },
    {
      test: 'supineRoll',
      performed: true,
      positive: false,
    },
  ],
  oculomotor: [
    { test: 'spontaneousNystagmus', performed: true, normal: true },
    { test: 'smoothPursuit', performed: true, normal: true },
    { test: 'saccades', performed: true, normal: true },
  ],
  vestibularFunction: [],
  balance: [
    { test: 'tandemStance', performed: true, surface: 'firm', eyes: 'open', timeSec: 30, lossOfBalance: false, assistanceRequired: 'none' },
  ],
  gait: [
    { test: 'dynamicGaitIndex', performed: true, score: 22, assistanceLevel: 'independent', symptomsProvoked: false },
  ],
  outcomeMeasures: [
    { test: 'dhi', score: 46 },
    { test: 'abc', score: 78 },
  ],
};

const mariaV1Interp = interpretFindings(mariaV1Results, mariaV1Subjective);

const mariaV1: Visit = {
  id: 'visit-maria-1',
  patientId: 'pt-maria',
  date: '2026-08-01',
  type: 'initialEvaluation',
  visitNumber: 1,
  subjective: mariaV1Subjective,
  redFlagScreen: noRedFlags,
  examRecommendations: acceptedRecs(mariaV1Subjective),
  results: mariaV1Results,
  interpretation: mariaV1Interp,
  treatmentPlan: acceptedPlan(mariaV1Interp),
  exercisePerformance: [],
  therapistNotes: 'Right Epley performed x2 in clinic; repeat Dix-Hallpike negative after second repositioning.',
};

const mariaV2Subjective: SubjectiveExam = {
  ...mariaV1Subjective,
  primaryComplaint: 'Rare, very mild lightheadedness; rolling and looking up no longer provoke spinning.',
  durations: [],
  triggers: [],
  additionalNotes: 'Overall significant improvement since last visit.',
};

const mariaV2Results: ExaminationResults = {
  positional: [
    { test: 'dixHallpike', performed: true, positive: false, side: 'right' },
  ],
  oculomotor: [
    { test: 'spontaneousNystagmus', performed: true, normal: true },
  ],
  vestibularFunction: [],
  balance: [
    { test: 'tandemStance', performed: true, surface: 'firm', eyes: 'open', timeSec: 30, lossOfBalance: false, assistanceRequired: 'none' },
  ],
  gait: [
    { test: 'dynamicGaitIndex', performed: true, score: 24, assistanceLevel: 'independent', symptomsProvoked: false },
  ],
  outcomeMeasures: [
    { test: 'dhi', score: 12 },
    { test: 'abc', score: 92 },
  ],
};

const mariaV2Interp = interpretFindings(mariaV2Results, mariaV2Subjective);

const mariaV2: Visit = {
  id: 'visit-maria-2',
  patientId: 'pt-maria',
  date: '2026-08-08',
  type: 'followUp',
  visitNumber: 2,
  subjective: mariaV2Subjective,
  redFlagScreen: noRedFlags,
  examRecommendations: acceptedRecs(mariaV2Subjective),
  results: mariaV2Results,
  interpretation: mariaV2Interp,
  treatmentPlan: [],
  exercisePerformance: [],
  interimHistory: 'Reports rolling in bed and looking up no longer provoke spinning; only rare, very mild lightheadedness remains.',
  therapistNotes: 'Dix-Hallpike negative bilaterally. Discharge from BPPV-specific treatment; monitor for recurrence.',
};

// ---------------------------------------------------------------------
// Patient 2: James Whitfield - left unilateral vestibular hypofunction
// ---------------------------------------------------------------------

const james: Patient = {
  id: 'pt-james',
  firstName: 'James',
  lastName: 'Whitfield',
  age: 68,
  sex: 'male',
  createdAt: '2026-06-15T09:00:00.000Z',
};

function jamesSubjective(overrides: Partial<SubjectiveExam> = {}): SubjectiveExam {
  return {
    primaryComplaint: 'Constant unsteadiness and blurring of vision when walking or turning head, since a viral illness 3 weeks ago.',
    symptomOnset: '3 weeks ago, following a viral illness',
    mechanismOfOnset: 'Post-viral, sudden onset of severe vertigo that has since settled into constant disequilibrium',
    medicalHistory: 'Type 2 diabetes, hyperlipidemia',
    medications: 'Metformin, atorvastatin',
    fallsHistory: 'One near-fall while turning quickly in the kitchen',
    assistiveDeviceUse: 'None currently, uses walls for support at home',
    symptoms: ['disequilibrium', 'oscillopsia', 'motionSensitivity', 'imbalance'],
    durations: ['constant'],
    triggers: ['headMovements', 'turning', 'busyVisualEnvironments', 'walking'],
    associatedSymptoms: ['nausea'],
    ...overrides,
  };
}

const jamesV1Subjective = jamesSubjective();

const jamesV1Results: ExaminationResults = {
  positional: [{ test: 'dixHallpike', performed: true, positive: false }],
  oculomotor: [
    { test: 'spontaneousNystagmus', performed: true, normal: false, findings: 'Subtle left-beating nystagmus, fixation-suppressible' },
    { test: 'gazeEvokedNystagmus', performed: true, normal: true },
    { test: 'smoothPursuit', performed: true, normal: true },
    { test: 'saccades', performed: true, normal: true },
    { test: 'skewDeviation', performed: true, normal: true },
    { test: 'vorCancellation', performed: true, normal: true },
  ],
  vestibularFunction: [
    { test: 'headImpulseTest', performed: true, normal: false, side: 'left', findings: 'Overt corrective saccade with leftward head thrust' },
    { test: 'dynamicVisualAcuity', performed: true, normal: false, linesLostDVA: 4 },
    { test: 'headShakingNystagmus', performed: true, normal: false, findings: 'Left-beating nystagmus after horizontal head-shake' },
  ],
  balance: [
    { test: 'mctsib', performed: true, surface: 'foam', eyes: 'closed', timeSec: 12, lossOfBalance: true, assistanceRequired: 'contact-guard' },
    { test: 'singleLegStance', performed: true, surface: 'firm', eyes: 'open', timeSec: 9, lossOfBalance: false, assistanceRequired: 'none' },
  ],
  gait: [
    { test: 'dynamicGaitIndex', performed: true, score: 16, assistanceLevel: 'contact-guard', deviations: 'Widened base with head turns, mild lateral step deviation', symptomsProvoked: true },
    { test: 'timedUpAndGo', performed: true, timeSec: 13.2, assistiveDevice: 'none', assistanceLevel: 'independent' },
  ],
  outcomeMeasures: [
    { test: 'dhi', score: 52 },
    { test: 'abc', score: 61 },
  ],
};

const jamesV1Interp = interpretFindings(jamesV1Results, jamesV1Subjective);

const jamesV1: Visit = {
  id: 'visit-james-1',
  patientId: 'pt-james',
  date: '2026-07-05',
  type: 'initialEvaluation',
  visitNumber: 1,
  subjective: jamesV1Subjective,
  redFlagScreen: noRedFlags,
  examRecommendations: acceptedRecs(jamesV1Subjective),
  results: jamesV1Results,
  interpretation: jamesV1Interp,
  treatmentPlan: acceptedPlan(jamesV1Interp),
  exercisePerformance: [
    {
      intervention: 'gazeStabilizationVOR1',
      visitId: 'visit-james-1',
      parameters: '60 BPM, 30 seconds, seated, plain background',
      symptomResponse: 'moderate',
      notes: 'Patient reported moderate dizziness during exercise, resolved within a minute of stopping.',
    },
  ],
};

const jamesV2Subjective = jamesSubjective({
  primaryComplaint: 'Some improvement in general steadiness; still notices blurring with quick head turns in busy environments.',
  fallsHistory: 'No falls since last visit',
});

const jamesV2Results: ExaminationResults = {
  ...jamesV1Results,
  vestibularFunction: [
    { test: 'headImpulseTest', performed: true, normal: false, side: 'left', findings: 'Corrective saccade present, smaller amplitude than initial visit' },
    { test: 'dynamicVisualAcuity', performed: true, normal: false, linesLostDVA: 3 },
  ],
  gait: [
    { test: 'dynamicGaitIndex', performed: true, score: 19, assistanceLevel: 'independent', deviations: 'Mild widened base with head turns', symptomsProvoked: true },
  ],
  outcomeMeasures: [
    { test: 'dhi', score: 38 },
    { test: 'abc', score: 70 },
  ],
};

const jamesV2Interp = interpretFindings(jamesV2Results, jamesV2Subjective);

const jamesV2: Visit = {
  id: 'visit-james-2',
  patientId: 'pt-james',
  date: '2026-07-19',
  type: 'followUp',
  visitNumber: 2,
  subjective: jamesV2Subjective,
  redFlagScreen: noRedFlags,
  examRecommendations: acceptedRecs(jamesV2Subjective),
  results: jamesV2Results,
  interpretation: jamesV2Interp,
  treatmentPlan: acceptedPlan(jamesV2Interp),
  exercisePerformance: [
    {
      intervention: 'gazeStabilizationVOR1',
      visitId: 'visit-james-2',
      parameters: '70 BPM, 45 seconds, seated, plain background',
      symptomResponse: 'moderate',
      notes: 'Tolerating slightly longer duration; still moderate symptoms toward end of set.',
    },
  ],
  interimHistory: 'Reports gradual improvement in general steadiness at home; still notices visual blurring with quick head turns in busy places like the grocery store.',
};

const jamesV3Subjective = jamesSubjective({
  primaryComplaint: 'Continued improvement; occasional mild unsteadiness only in very busy or dark environments.',
  triggers: ['busyVisualEnvironments', 'darkness'],
  fallsHistory: 'No falls since last visit',
});

const jamesV3Results: ExaminationResults = {
  ...jamesV2Results,
  vestibularFunction: [
    { test: 'headImpulseTest', performed: true, normal: false, side: 'left', findings: 'Small corrective saccade, improved from prior visits' },
    { test: 'dynamicVisualAcuity', performed: true, normal: false, linesLostDVA: 2 },
  ],
  gait: [
    { test: 'dynamicGaitIndex', performed: true, score: 22, assistanceLevel: 'independent', deviations: 'Minimal deviation with head turns', symptomsProvoked: false },
  ],
  outcomeMeasures: [
    { test: 'dhi', score: 22 },
    { test: 'abc', score: 80 },
  ],
};

const jamesV3Interp = interpretFindings(jamesV3Results, jamesV3Subjective);

const jamesV3: Visit = {
  id: 'visit-james-3',
  patientId: 'pt-james',
  date: '2026-08-02',
  type: 'followUp',
  visitNumber: 3,
  subjective: jamesV3Subjective,
  redFlagScreen: noRedFlags,
  examRecommendations: acceptedRecs(jamesV3Subjective),
  results: jamesV3Results,
  interpretation: jamesV3Interp,
  treatmentPlan: acceptedPlan(jamesV3Interp),
  exercisePerformance: [
    {
      intervention: 'gazeStabilizationVOR1',
      visitId: 'visit-james-3',
      parameters: '80 BPM, 60 seconds, seated, plain background',
      symptomResponse: 'mild',
      notes: 'Good tolerance; only mild symptoms reported, resolving quickly.',
    },
  ],
  interimHistory: 'Continued improvement; only mild unsteadiness remains in very busy or dark environments.',
};

// ---------------------------------------------------------------------
// Patient 3: Eleanor Brooks - bilateral vestibular hypofunction
// ---------------------------------------------------------------------

const eleanor: Patient = {
  id: 'pt-eleanor',
  firstName: 'Eleanor',
  lastName: 'Brooks',
  age: 75,
  sex: 'female',
  createdAt: '2026-06-01T09:00:00.000Z',
};

function eleanorSubjective(overrides: Partial<SubjectiveExam> = {}): SubjectiveExam {
  return {
    primaryComplaint: 'Chronic unsteadiness, worse in the dark or on uneven ground, with visual blurring when walking.',
    symptomOnset: 'Gradual onset over the past year, following chemotherapy treatment 18 months ago',
    mechanismOfOnset: 'Suspected ototoxic effect of prior chemotherapy',
    medicalHistory: 'History of breast cancer (treated), osteoporosis, prior chemotherapy',
    medications: 'Calcium/vitamin D, alendronate',
    fallsHistory: '2 falls in the past 6 months, both at home on uneven flooring',
    assistiveDeviceUse: 'Single-point cane for community ambulation',
    symptoms: ['disequilibrium', 'oscillopsia', 'imbalance', 'motionSensitivity'],
    durations: ['constant'],
    triggers: ['darkness', 'unevenSurfaces', 'walking', 'turning'],
    associatedSymptoms: [],
    ...overrides,
  };
}

const eleanorV1Subjective = eleanorSubjective();

const eleanorV1Results: ExaminationResults = {
  positional: [{ test: 'dixHallpike', performed: true, positive: false }],
  oculomotor: [
    { test: 'spontaneousNystagmus', performed: true, normal: true },
    { test: 'smoothPursuit', performed: true, normal: true },
    { test: 'saccades', performed: true, normal: true },
  ],
  vestibularFunction: [
    { test: 'headImpulseTest', performed: true, normal: false, side: 'bilateral', findings: 'Bilateral corrective saccades, right slightly more prominent than left' },
    { test: 'dynamicVisualAcuity', performed: true, normal: false, linesLostDVA: 5 },
  ],
  balance: [
    { test: 'romberg', performed: true, surface: 'firm', eyes: 'closed', timeSec: 8, lossOfBalance: true, assistanceRequired: 'contact-guard' },
    { test: 'mctsib', performed: true, surface: 'foam', eyes: 'closed', timeSec: 6, lossOfBalance: true, assistanceRequired: 'moderate' },
  ],
  gait: [
    { test: 'functionalGaitAssessment', performed: true, score: 14, assistiveDevice: 'single-point cane', assistanceLevel: 'contact-guard', deviations: 'Widened base, reduced trunk rotation, hesitancy on foam and with head turns', symptomsProvoked: true },
    { test: 'timedUpAndGo', performed: true, timeSec: 16.8, assistiveDevice: 'single-point cane', assistanceLevel: 'independent' },
  ],
  outcomeMeasures: [
    { test: 'dhi', score: 60 },
    { test: 'abc', score: 45 },
  ],
};

const eleanorV1Interp = interpretFindings(eleanorV1Results, eleanorV1Subjective);

const eleanorV1: Visit = {
  id: 'visit-eleanor-1',
  patientId: 'pt-eleanor',
  date: '2026-07-12',
  type: 'initialEvaluation',
  visitNumber: 1,
  subjective: eleanorV1Subjective,
  redFlagScreen: noRedFlags,
  examRecommendations: acceptedRecs(eleanorV1Subjective),
  results: eleanorV1Results,
  interpretation: eleanorV1Interp,
  treatmentPlan: acceptedPlan(eleanorV1Interp),
  exercisePerformance: [
    {
      intervention: 'staticBalanceTraining',
      visitId: 'visit-eleanor-1',
      parameters: 'Firm surface, feet shoulder-width, eyes open, 30 seconds x4',
      symptomResponse: 'mild',
    },
  ],
};

const eleanorV2Subjective = eleanorSubjective({
  primaryComplaint: 'Slightly more confident with static standing; still very cautious walking on uneven or dark surfaces.',
  fallsHistory: 'No falls since last visit',
});

const eleanorV2Results: ExaminationResults = {
  ...eleanorV1Results,
  balance: [
    { test: 'romberg', performed: true, surface: 'firm', eyes: 'closed', timeSec: 15, lossOfBalance: false, assistanceRequired: 'none' },
    { test: 'mctsib', performed: true, surface: 'foam', eyes: 'closed', timeSec: 9, lossOfBalance: true, assistanceRequired: 'contact-guard' },
  ],
  gait: [
    { test: 'functionalGaitAssessment', performed: true, score: 17, assistiveDevice: 'single-point cane', assistanceLevel: 'contact-guard', deviations: 'Improved trunk rotation; still hesitant with head turns', symptomsProvoked: true },
    { test: 'timedUpAndGo', performed: true, timeSec: 14.9, assistiveDevice: 'single-point cane', assistanceLevel: 'independent' },
  ],
  outcomeMeasures: [
    { test: 'dhi', score: 55 },
    { test: 'abc', score: 50 },
  ],
};

const eleanorV2Interp = interpretFindings(eleanorV2Results, eleanorV2Subjective);

const eleanorV2: Visit = {
  id: 'visit-eleanor-2',
  patientId: 'pt-eleanor',
  date: '2026-08-09',
  type: 'followUp',
  visitNumber: 2,
  subjective: eleanorV2Subjective,
  redFlagScreen: noRedFlags,
  examRecommendations: acceptedRecs(eleanorV2Subjective),
  results: eleanorV2Results,
  interpretation: eleanorV2Interp,
  treatmentPlan: acceptedPlan(eleanorV2Interp),
  exercisePerformance: [
    {
      intervention: 'staticBalanceTraining',
      visitId: 'visit-eleanor-2',
      parameters: 'Firm surface, feet together, eyes open, 30 seconds x4',
      symptomResponse: 'mild',
    },
  ],
  interimHistory: 'Feels slightly steadier standing still; remains very cautious walking on uneven or dark surfaces and has not resumed unsupervised community outings.',
};

// ---------------------------------------------------------------------
// Patient 4: Robert Kim - red flag screening demo (exam appropriately halted)
// ---------------------------------------------------------------------

const robert: Patient = {
  id: 'pt-robert',
  firstName: 'Robert',
  lastName: 'Kim',
  age: 61,
  sex: 'male',
  createdAt: '2026-08-20T09:00:00.000Z',
};

const robertSubjective: SubjectiveExam = {
  primaryComplaint: 'Sudden severe dizziness this morning with new numbness on the left side and difficulty speaking clearly.',
  symptomOnset: 'This morning, sudden',
  mechanismOfOnset: 'Spontaneous, no clear trigger reported',
  medicalHistory: 'Hypertension, atrial fibrillation',
  medications: 'Apixaban, metoprolol',
  fallsHistory: 'Unable to safely assess - patient reports near-fall this morning',
  assistiveDeviceUse: 'None prior to today',
  symptoms: ['vertigo', 'imbalance'],
  durations: ['constant'],
  triggers: [],
  associatedSymptoms: ['headache', 'neurologicSymptoms'],
  additionalNotes: 'Family reports patient "not making sense" briefly this morning.',
};

const robertRedFlags: RedFlagScreen = {
  findings: ['dysarthria', 'newNumbness', 'newSevereHeadache'],
  otherDescription: 'Family also reports transient word-finding difficulty this morning.',
  therapistAcknowledgement: true,
};

const robertV1: Visit = {
  id: 'visit-robert-1',
  patientId: 'pt-robert',
  date: '2026-08-25',
  type: 'initialEvaluation',
  visitNumber: 1,
  subjective: robertSubjective,
  redFlagScreen: robertRedFlags,
  examRecommendations: [],
  results: emptyResults(),
  interpretation: null,
  treatmentPlan: [],
  exercisePerformance: [],
  therapistNotes:
    'Red flags identified on screening (dysarthria, new numbness, new severe headache). Routine vestibular exam stopped; patient referred for emergency medical evaluation per red flag protocol. Do not resume routine PT exam without medical clearance.',
};

// ---------------------------------------------------------------------
// Patient 5: Susan Patel - findings raising possible central involvement
// (no hard ER-level red flags, but oculomotor findings + migraine history)
// ---------------------------------------------------------------------

const susan: Patient = {
  id: 'pt-susan',
  firstName: 'Susan',
  lastName: 'Patel',
  age: 45,
  sex: 'female',
  createdAt: '2026-08-18T09:00:00.000Z',
};

const susanSubjective: SubjectiveExam = {
  primaryComplaint: 'Recurrent episodes of dizziness lasting hours, often with headache, sensitivity to light, and mild imbalance between episodes.',
  symptomOnset: 'Recurrent over the past 4 months',
  mechanismOfOnset: 'Spontaneous episodes, no consistent trigger identified',
  medicalHistory: 'Long-standing history of migraine headaches',
  medications: 'Sumatriptan as needed',
  fallsHistory: 'No falls',
  assistiveDeviceUse: 'None',
  symptoms: ['dizziness', 'lightheadedness', 'motionSensitivity'],
  durations: ['hours'],
  triggers: ['busyVisualEnvironments', 'darkness'],
  associatedSymptoms: ['headache', 'migraineHistory', 'nausea'],
  additionalNotes: 'Denies focal weakness, numbness, or speech changes during episodes; today is an inter-episode visit.',
};

const susanResults: ExaminationResults = {
  positional: [{ test: 'dixHallpike', performed: true, positive: false }],
  oculomotor: [
    { test: 'spontaneousNystagmus', performed: true, normal: true },
    { test: 'gazeEvokedNystagmus', performed: true, normal: false, findings: 'Mild direction-changing gaze-evoked nystagmus' },
    { test: 'smoothPursuit', performed: true, normal: false, findings: 'Saccadic pursuit bilaterally' },
    { test: 'saccades', performed: true, normal: true },
    { test: 'skewDeviation', performed: true, normal: true },
  ],
  vestibularFunction: [
    { test: 'headImpulseTest', performed: true, normal: true, side: 'n/a' },
  ],
  balance: [
    { test: 'tandemStance', performed: true, surface: 'firm', eyes: 'open', timeSec: 25, lossOfBalance: false, assistanceRequired: 'none' },
  ],
  gait: [
    { test: 'dynamicGaitIndex', performed: true, score: 20, assistanceLevel: 'independent', symptomsProvoked: true, deviations: 'Mild unsteadiness with head turns' },
  ],
  outcomeMeasures: [
    { test: 'dhi', score: 58 },
    { test: 'abc', score: 55 },
  ],
};

const susanInterp = interpretFindings(susanResults, susanSubjective);

const susanV1: Visit = {
  id: 'visit-susan-1',
  patientId: 'pt-susan',
  date: '2026-08-22',
  type: 'initialEvaluation',
  visitNumber: 1,
  subjective: susanSubjective,
  redFlagScreen: { findings: [], therapistAcknowledgement: true },
  examRecommendations: acceptedRecs(susanSubjective),
  results: susanResults,
  interpretation: susanInterp,
  treatmentPlan: acceptedPlan(susanInterp),
  exercisePerformance: [],
  therapistNotes:
    'Discussed findings with patient. Recommended communication with treating physician regarding vestibular migraine given oculomotor findings and headache history before initiating an aggressive vestibular rehab program.',
};

// ---------------------------------------------------------------------
// Patient 6: Diane Foster - nonspecific balance/vestibular dysfunction
// ---------------------------------------------------------------------

const diane: Patient = {
  id: 'pt-diane',
  firstName: 'Diane',
  lastName: 'Foster',
  age: 39,
  sex: 'female',
  createdAt: '2026-07-22T09:00:00.000Z',
};

function dianeSubjective(overrides: Partial<SubjectiveExam> = {}): SubjectiveExam {
  return {
    primaryComplaint: 'General unsteadiness and fatigue with balance since a mild concussion 6 weeks ago.',
    symptomOnset: '6 weeks ago, following a minor fall with head strike',
    mechanismOfOnset: 'Mild traumatic brain injury (concussion), no loss of consciousness',
    medicalHistory: 'Otherwise healthy',
    medications: 'Occasional ibuprofen',
    fallsHistory: 'No falls since the initial injury',
    assistiveDeviceUse: 'None',
    symptoms: ['disequilibrium', 'imbalance'],
    durations: ['constant'],
    triggers: ['busyVisualEnvironments', 'unevenSurfaces'],
    associatedSymptoms: ['headache'],
    ...overrides,
  };
}

const dianeV1Subjective = dianeSubjective();

const dianeV1Results: ExaminationResults = {
  positional: [{ test: 'dixHallpike', performed: true, positive: false }],
  oculomotor: [
    { test: 'spontaneousNystagmus', performed: true, normal: true },
    { test: 'smoothPursuit', performed: true, normal: true },
    { test: 'saccades', performed: true, normal: true },
  ],
  vestibularFunction: [
    { test: 'headImpulseTest', performed: true, normal: true, side: 'n/a' },
  ],
  balance: [
    { test: 'mctsib', performed: true, surface: 'foam', eyes: 'closed', timeSec: 14, lossOfBalance: true, assistanceRequired: 'contact-guard' },
  ],
  gait: [
    { test: 'dynamicGaitIndex', performed: true, score: 18, assistanceLevel: 'independent', symptomsProvoked: true, deviations: 'Mild unsteadiness in busy visual environment simulation' },
  ],
  outcomeMeasures: [
    { test: 'dhi', score: 34 },
    { test: 'abc', score: 68 },
  ],
};

const dianeV1Interp = interpretFindings(dianeV1Results, dianeV1Subjective);

const dianeV1: Visit = {
  id: 'visit-diane-1',
  patientId: 'pt-diane',
  date: '2026-08-05',
  type: 'initialEvaluation',
  visitNumber: 1,
  subjective: dianeV1Subjective,
  redFlagScreen: noRedFlags,
  examRecommendations: acceptedRecs(dianeV1Subjective),
  results: dianeV1Results,
  interpretation: dianeV1Interp,
  treatmentPlan: acceptedPlan(dianeV1Interp),
  exercisePerformance: [
    {
      intervention: 'multisensoryBalanceTraining',
      visitId: 'visit-diane-1',
      parameters: 'Foam surface, eyes open, 30 seconds x3',
      symptomResponse: 'mild',
    },
  ],
};

const dianeV2Subjective = dianeSubjective({
  primaryComplaint: 'Feeling about the same as last visit; still gets unsteady in crowded/busy places.',
});

const dianeV2Results: ExaminationResults = {
  ...dianeV1Results,
  balance: [
    { test: 'mctsib', performed: true, surface: 'foam', eyes: 'closed', timeSec: 15, lossOfBalance: true, assistanceRequired: 'contact-guard' },
  ],
  gait: [
    { test: 'dynamicGaitIndex', performed: true, score: 18, assistanceLevel: 'independent', symptomsProvoked: true, deviations: 'Similar to last visit' },
  ],
  outcomeMeasures: [
    { test: 'dhi', score: 33 },
    { test: 'abc', score: 69 },
  ],
};

const dianeV2Interp = interpretFindings(dianeV2Results, dianeV2Subjective);

const dianeV2: Visit = {
  id: 'visit-diane-2',
  patientId: 'pt-diane',
  date: '2026-08-19',
  type: 'followUp',
  visitNumber: 2,
  subjective: dianeV2Subjective,
  redFlagScreen: noRedFlags,
  examRecommendations: acceptedRecs(dianeV2Subjective),
  results: dianeV2Results,
  interpretation: dianeV2Interp,
  treatmentPlan: acceptedPlan(dianeV2Interp),
  exercisePerformance: [
    {
      intervention: 'multisensoryBalanceTraining',
      visitId: 'visit-diane-2',
      parameters: 'Foam surface, eyes open, 30 seconds x3',
      symptomResponse: 'mild',
    },
  ],
  interimHistory: 'Feels about the same as last visit overall; balance in crowded or busy places remains the primary limiter.',
};

export const seedPatients: Patient[] = [maria, james, eleanor, robert, susan, diane];

export const seedVisits: Visit[] = [
  mariaV1,
  mariaV2,
  jamesV1,
  jamesV2,
  jamesV3,
  eleanorV1,
  eleanorV2,
  robertV1,
  susanV1,
  dianeV1,
  dianeV2,
];
